# Site settings
title: "Yet to Define"
logo: logo.jpeg
logo_chick : chick.png  # https://www.flaticon.com/free-icon/chick_789473#term=chick&page=1&position=20
email: dnwdjqldb@naver.com
description: > # this means to ignore newlines until "url:"
  About <br>게임웹서비스개발팀 <br> NHN Corporation<br>
url: "https://SeonheeKim.github.io" # the base hostname & protocol for your site
baseurl: / # the subpath of your site, e.g. /blog/
github_username:  SeonheeKim

permalink: pretty
paginate: 5

# Build settings
markdown: kramdown
highlighter: rouge

gems:
  - jekyll-sitemap
  - jekyll-paginate
