# Site settings
title: "Yet to Define"
logo: logo.jpeg
logo_chick : chick.png
email: dnwdjqldb@naver.com
description: > # this means to ignore newlines until "url:"
  About <br> NHN Entertainment <br>
url: "http://SeonheeKim.github.io" # the base hostname & protocol for your site
baseurl: /SeonheeKim.github.io # the subpath of your site, e.g. /blog/
twitter_username: jekyllrb
github_username:  SeonheeKim

permalink: pretty
paginate: 5

# Build settings
markdown: kramdown
highlighter: rouge

gems:
  - jekyll-sitemap
  - jekyll-paginate
